[tool.poetry]
name = "Automation Module for SentinelOne"
description = ""
version = "0.0"
authors = []

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
sekoia-automation-sdk = "^1.13.0"
orjson = "^3.7.7"
sentinelone-management-sdk = {path = "sentinel-mgmt-sdk.tar.gz"}
confluent-kafka = "^2.1.1"
certifi = "^2023.7.22"
protobuf = "^4.21.9"
structlog = "^24.4.0"
stix2-patterns = "^2.0.0"
pandas = "^2.2.2"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
requests = "*"
requests-mock = "*"
freezegun = "*"

[tool.poetry.group.dev.dependencies]
mypy = "^0.990"

[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 119

[tool.coverage.run]
omit = [
    "tests/*",
    "main.py",
]
