[tool.poetry]
name = "Automation module for Office365"
description = ""
version = "0.0"
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
sekoia-automation-sdk = "^1.8.1"
orjson = "^3.7.7"
tenacity = "^8.0.1"
msal = "^1.18.0"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
requests = "*"
requests-mock = "*"

[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 119

[tool.black]
line-length = 119
target-version = ['py310']
include = '\.pyi?$'

[tool.coverage.run]
omit = [
    "tests/*",
    "main.py",
]
