name: Check linting
on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        id: setup-python
        with:
          python-version: "3.10"

      - uses: actions/checkout@v3

      - name: Install
        run: npm install -g prettier

      - name: Run
        working-directory: .
        run: |
          python linter.py check --changes
